// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaT42-hBRfPK2U4VKyquEZWobRK6QRfEM',
    appId: '1:907777869327:web:83df5ccff4bc345178c57a',
    messagingSenderId: '907777869327',
    projectId: 'smart-shopping-list-d91fd',
    authDomain: 'smart-shopping-list-d91fd.firebaseapp.com',
    storageBucket: 'smart-shopping-list-d91fd.firebasestorage.app',
    measurementId: 'G-CEWLP2NSN9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBczbArhxVsFlLm0pDFOZ4fz9Xg63jCNl4',
    appId: '1:907777869327:android:985b7fe2348858db78c57a',
    messagingSenderId: '907777869327',
    projectId: 'smart-shopping-list-d91fd',
    storageBucket: 'smart-shopping-list-d91fd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRePlxKqbXeHkaST_u40EuE1YLIybr-H8',
    appId: '1:907777869327:ios:211f62d4d872054478c57a',
    messagingSenderId: '907777869327',
    projectId: 'smart-shopping-list-d91fd',
    storageBucket: 'smart-shopping-list-d91fd.firebasestorage.app',
    androidClientId: '907777869327-uje8gnvmhnr8suqs2epn36rvicm8vlla.apps.googleusercontent.com',
    iosClientId: '907777869327-518nn1vrnog2drq80tt5af4bfrbp0bpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShoppingList',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRePlxKqbXeHkaST_u40EuE1YLIybr-H8',
    appId: '1:907777869327:ios:211f62d4d872054478c57a',
    messagingSenderId: '907777869327',
    projectId: 'smart-shopping-list-d91fd',
    storageBucket: 'smart-shopping-list-d91fd.firebasestorage.app',
    androidClientId: '907777869327-uje8gnvmhnr8suqs2epn36rvicm8vlla.apps.googleusercontent.com',
    iosClientId: '907777869327-518nn1vrnog2drq80tt5af4bfrbp0bpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartShoppingList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaT42-hBRfPK2U4VKyquEZWobRK6QRfEM',
    appId: '1:907777869327:web:8593366baba8afe878c57a',
    messagingSenderId: '907777869327',
    projectId: 'smart-shopping-list-d91fd',
    authDomain: 'smart-shopping-list-d91fd.firebaseapp.com',
    storageBucket: 'smart-shopping-list-d91fd.firebasestorage.app',
    measurementId: 'G-9QZ76SLQK6',
  );
}
